version: "3"

services:
  nominatim:
    image: mediagis/nominatim:4.3
    container_name: nominatim
    ports:
      - "8080:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/asia/vietnam-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/vietnam-updates/
      NOMINATIM_PASSWORD: very_secure_password
      IMPORT_WIKIPEDIA: "false"
      IMPORT_US_POSTCODES: "false"
      IMPORT_GB_POSTCODES: "false"
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1gb

volumes:
  nominatim-data:
